services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:?Mongo username is required}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:?Mongo password is required}
    volumes:
      - mongo-data:/data/db
        
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
        
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
        
volumes:
  postgres-data:
  mongo-data:
  rabbitmq-data:  