name: Tests Pipeline

on:
  workflow_call:
    project-path:
      required: true
      type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: ${{ inputs.project-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore dependencies
        run: dotnet restore $PROJECT_PATH

      - name: Run Tests
        run: dotnet test $PROJECT_PATH --no-restore --verbosity normal