name: Deploy to Azure Pipeline Template

on:
  workflow_call: 
    inputs: 
      service-name: 
        required: true
        type: string
      docker-image-tag: 
        required: true
        type: string
      k8s-manifest-path: 
        required: true
        type: string
    secrets: 
      AZURE_CREDENTIALS:  
        required: true
      KUBCONFIG:     
        required: true
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      KUBE_CONFIG: ${{ secrets.KUBCONFIG }}
      SERVICE_NAME: ${{ inputs.service-name }}
      DOCKER_IMAGE_TAG: ${{ inputs.docker-image-tag }}
      K8S_MANIFEST_PATH: ${{ inputs.k8s-manifest-path }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set up kubectl
        run: |
          echo "$KUBE_CONFIG" | base64 --decode > subconfig
          export KUBE_CONFIG=subconfig
          kubectl config use-context aks
          
      - name: Update Kubernetes Manifest
        run: |
          sed -i 's|image: .*|image: $SERVICE_NAME:$DOCKER_IMAGE_TAG|g' $K8S_MANIFEST_PATH
          
      - name: Deploy to Kubernetes
        run: kubectl apply -f $K8S_MANIFEST_PATH