name: Dependency Check Template

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write  
  
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - uses: actions/dependency-review-actions@v4
        with:
          comment-summary-in-pr: always
        