name: Terraform Template

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: "prod"
    secrets:
      TF_CLOUD_TOKEN:
        required: true

jobs: 
  terraform:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      TF_CLOUD_TOKEN: ${{ secrets.TF_CLOUD_TOKEN }}
    defaults: 
      run:
        working-directory: terraform/environments/$ENVIRONMENT
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Code Validate
        run: terraform validate
        
      - name: Terraform Plan
        run: |
          export TF_CLOUD_TOKEN=$TF_CLOUD_TOKEN
          terraform plan -out=tfplan
        
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan