name: Versioning Template

on:
  workflow_call:
    inputs:
      version-file:
        required: true
        type: string
      project-path:
        required: true
        type: string
        
jobs:
  versioning:
    runs-on: ubuntu-latest
    name: Versioning
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ${{ inputs.project-path }}
    env:
      VERSION_FILE: ${{ inputs.version-file }}
   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Download Previous Version (if exists)
        uses: actions/download-artifact@v4
        with:
          name: version
        continue-on-error: true
          
      - name: Ensure Version File Exists
        run: |
          if [ ! -f $VERSION_FILE ]; then
            echo "0.0.0" > $VERSION_FILE
          fi
          
      - name: Extract Current Version
        run: |
          VERSION=$(cat $VERSION_FILE)
          echo "current_version=$VERSION" >> $GITHUB_ENV
          
      - name: Increment Version
        id: increment_version
        run: |
          IFS='.' read -r -MAJOR MINOR PATCH < <(echo "${current_version}")
          PATCH=$((PATCH + 1))
          echo "new_version=$MAJOR.$MINOR.$PATCH" >> $GITHUB_ENV
          
      - name: Save Version as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: $VERSION_FILE